# Site settings
title: "Dizzy Updates.Net"
description: "Avenue of news and more"
url: "http://www.dizzyupdates.net"
author:
  name: "Qwesi Dizzy"
  email: "qwesidizzy3@gmail.com"
  url:   "http://www.dizzyupdates.net"

# Build settings
baseurl: /Dizzy-Updates # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

  paginate: 5 # Number of posts per page
  paginate_path: "/page:num/"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
